### ISSUE TITLE
TypeError: vestingWallet.released is not a function

### ISSUE THREAD

**Issue by billtlee** [OpenZeppelin/openzeppelin-contracts-upgradeable#153]
Trying to implement vestingWallet with cliff.

**💻 Environment**

    "@openzeppelin/contracts-upgradeable": "^4.5.2"
  Using Hardhat
  This actually works on remix

**📝 Details**

**🔢 Code to reproduce bug**

DualVestingWallet.sol
```
//SPDX-License-Identifier: MIT
pragma solidity ^0.8;

import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts-upgradeable/finance/VestingWalletUpgradeable.sol";

contract DualVestingWallet is Initializable, VestingWalletUpgradeable {
    uint64 private _cliff;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    function initialize(
        address beneficiaryAddress,
        uint64 startTimestamp,
        uint64 durationSeconds,
        uint64 cliff
    ) public initializer {
        _cliff = cliff;
        __VestingWallet_init(
            beneficiaryAddress,
            startTimestamp,
            durationSeconds
        );
    }

    function _vestingSchedule(uint256 totalAllocation, uint64 timestamp)
        internal
        view
        virtual
        override
        returns (uint256)
    {
        if (timestamp < start() + _cliff) {
            return 0;
        } else if (timestamp > start() + duration()) {
            return totalAllocation;
        } else {
            return (totalAllocation * (timestamp - start())) / duration();
        }
    }
}
```

DualVestingWallet-test.js
```
const { expect } = require('chai');
const { ethers, upgrades, artifacts } = require('hardhat');
const {
  BN,
  constants,
  expectEvent,
  expectRevert,
  time,
  balance,
} = require('@openzeppelin/test-helpers');
const { inTransaction } = require('@openzeppelin/test-helpers/src/expectEvent');

const { ZERO_ADDRESS } = constants;

before(async function () {
  // Advance to the next block to correctly read time in the solidity "now" function interpreted by ganache
  await time.advanceBlock();
});

beforeEach(async () => {
  [owner, user1, user2, ...users] = await ethers.getSigners();
  const Token = await ethers.getContractFactory('Token', owner);
  dual = await upgrades.deployProxy(Token, ['DualMint', 'DUAL']);
  const VestingWallet = await ethers.getContractFactory(
    'DualVestingWallet',
    owner
  );

  const startTimestamp = Math.floor(Date.now() / 1000);

  vestingWallet = await upgrades.deployProxy(VestingWallet, [
    owner.address,
    startTimestamp,
    7200,
    3600,
  ]);
});

describe('VestingWallet', async () => {
  it('release after cliff', async () => {
    await dual.mint(vestingWallet.address, 1000);
    await time.increase(time.duration.hours(5));
    console.log('vestingWallet address: ', vestingWallet.address);
    console.log('beneficiary: ', await vestingWallet.beneficiary());
    console.log('duration: ', await vestingWallet.duration());
    console.log('start: ', await vestingWallet.start());
    console.log('vested amount: ', await vestingWallet.vestedAmount());
    console.log('released: ', await vestingWallet.released());
    await vestingWallet.release(dual.address);
  });
});

```

then run test with
npx hardhat test ./test/DualVestingWallet-test.js

and got the following output:

```
  VestingWallet
vestingWallet address:  0x96F3Ce39Ad2BfDCf92C0F6E2C2CAbF83874660Fc
beneficiary:  0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
duration:  BigNumber { value: "7200" }
start:  BigNumber { value: "1647237136" }
    1) release after cliff


  0 passing (7s)
  1 failing

  1) VestingWallet
       release after cliff:
     TypeError: vestingWallet.vestedAmount is not a function
      at Context.<anonymous> (test/DualVestingWallet-test.js:47:56)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at runNextTicks (internal/process/task_queues.js:62:3)
      at listOnTimeout (internal/timers.js:523:9)
      at processTimers (internal/timers.js:497:7)
```

**Comment by Amxx** [comment]
Hello @billtlee 

There are two `vestedAmount` functions:
- `vestedAmount(uint64)`, that returns the amount of ether that is vested
- `vestedAmount(address,uint64)`, that returns the amount of token that is vested.

You may need to identify the function you want to call more precisely, by doing `vestingWallet['vestedAmount(uint64)']`. Also, you'll need to add an argument to that call.

**Comment by Amxx** [comment]
For your implementation, you could also be doing

```
    function _vestingSchedule(uint256 totalAllocation, uint64 timestamp)
        internal
        view
        virtual
        override
        returns (uint256)
    {
        return timestamp < start() + _cliff
            ? 0
            : super._vestingSchedule(totalAllocation, timestamp);
    }
```

**Comment by billtlee** [comment]
Thanks @Amxx!  Love the ternary alternative.  However, the calls are still not working.  It's my bad with the missing argument.  But the released() 
`console.log('released: ', await vestingWallet.released());`
function which takes no argument is also failing (if I take out the vestedAmount call all together).

**Comment by Amxx** [comment]
It's for the exact same reason. There are 2 variants of the `release` function and you been to say which want you use

https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/finance/VestingWalletUpgradeable.sol#L81-L93

**Comment by billtlee** [comment]
@Amxx OMG, you are a life saver!  I have been pulling my hair out all weekend.  Didn't know there is a special syntax to call overloaded functions in ethers.  Thanks!
